### PR TITLE
Migrate to null safety

### LINKED ISSUE #41: Migrating to null safety
I was wondering if there are any plans to migrate this package to null safety?

I would be happy to have an attempt at null safety migration if there are not.

### PR DESCRIPTION
**Pull request by xvrh**
Fixes #41

### CODE REVIEW

**Comment by kevmoo** [comment]
Need to drop dart 2.3 from CI

**Comment by kevmoo** [comment]
You'll have to rebase on latest, @xvrh

**Comment by xvrh** [comment]
@kevmoo This is rebased now!

**Comment by jakemac53** [comment]
I did this as well without realizing this PR was out heh, but I just pushed up my additional changes which were just to update the changelog and pubspec.

**Comment by jakemac53** [comment]
I am merging this internally as an extra check and once that succeeds I will push a PR to release it

**Pull request merged**
